// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_AT_DotNet.Data;

#nullable disable

namespace Projeto_AT_DotNet.Migrations
{
    [DbContext(typeof(AgenciaContext))]
    [Migration("20251001043708_AddIsDeletedToCliente")]
    partial class AddIsDeletedToCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Projeto_AT_DotNet.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Projeto_AT_DotNet.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("Projeto_AT_DotNet.Models.DestinoPacote", b =>
                {
                    b.Property<int>("PacoteTuristicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PacoteTuristicoId", "DestinoId");

                    b.HasIndex("DestinoId");

                    b.ToTable("DestinoPacotes");
                });

            modelBuilder.Entity("Projeto_AT_DotNet.Models.PacoteTuristico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantesAtuais")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoDiaria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PacotesTuristico");
                });

            modelBuilder.Entity("Projeto_AT_DotNet.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("TEXT");

                    b.Property<int>("PacoteTuristicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PacoteTuristicoId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Projeto_AT_DotNet.Models.DestinoPacote", b =>
                {
                    b.HasOne("Projeto_AT_DotNet.Models.Destino", "Destino")
                        .WithMany("PacotesAssociados")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_AT_DotNet.Models.PacoteTuristico", "PacoteTuristico")
                        .WithMany("DestinosIncluidos")
                        .HasForeignKey("PacoteTuristicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("PacoteTuristico");
                });

            modelBuilder.Entity("Projeto_AT_DotNet.Models.Reserva", b =>
                {
                    b.HasOne("Projeto_AT_DotNet.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_AT_DotNet.Models.PacoteTuristico", "PacoteTuristico")
                        .WithMany("Reservas")
                        .HasForeignKey("PacoteTuristicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PacoteTuristico");
                });

            modelBuilder.Entity("Projeto_AT_DotNet.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Projeto_AT_DotNet.Models.Destino", b =>
                {
                    b.Navigation("PacotesAssociados");
                });

            modelBuilder.Entity("Projeto_AT_DotNet.Models.PacoteTuristico", b =>
                {
                    b.Navigation("DestinosIncluidos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
